language: node_js
node_js:
  - "0.10"

services: mongodb

before_script:
  - npm install -g gulp jasmine-node
  - npm install

script:
  - gulp build
  - jasmine-node ./server/spec --verbose --forceexit